name: Merge Conflict PRs

on:
  workflow_dispatch:

jobs:
  get_date_time:
    name: Get Date/Time
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: date_time
        with:
          result-encoding: string
          retries: 3
          script: return JSON.stringify(new Date())
    outputs:
      date_time: ${{ steps.date_time.outputs.result }}
      
  create:
    name: Create
    needs: get_date_time
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file_name: ['File1.txt']
        file_content: ['Hello World! ${{ needs.get_date_time.outputs.date_time }}', 'Hello Mars! ${{ needs.get_date_time.outputs.date_time }}']
    steps:
    - uses: actions/checkout@v3
    - id: create-pr
      uses: octodemo/mq-demo/.github/actions/create-pr@main
      with:
        file_name: ${{ matrix.file_name }}
        file_content: ${{ matrix.file_content }}
        token: ${{ secrets.AUSTEN_PAT }}
    - run: gh pr merge ${{ steps.create-pr.outputs.pr_number }}
      env:
        GH_TOKEN: ${{ secrets.AUSTEN_PAT }}